2026-01-06T19-01

diff --git a/.github/workflows/nvchecker.yml b/.github/workflows/nvchecker.yml
--- a/.github/workflows/nvchecker.yml
+++ b/.github/workflows/nvchecker.yml
@@ -17,16 +17,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Install system dependencies
-      #   run: |
-      #     set -e
-      #     sudo apt-get update
-      #     sudo apt-get install -y \
-      #       python3-pip \
-      #       jq \
-      #       git \
-      #       curl
-
       - name: Install nvchecker
         run: |
           set -e
@@ -107,7 +97,7 @@ jobs:
             fi
 
             # 2. Create Branch and Commit
-            git switch master
+            git switch "${{ github.head_ref || github.ref_name }}"
             git switch -c "$branch_name"
 
             # Update the specific entry in oldver and newver files
@@ -119,23 +109,32 @@ jobs:
             git push origin "$branch_name"
 
             # 3. Prepare PR Body
-            pr_body="Automated update for **$entry** from \`$old_version\` to \`$new_version\`."
+            pr_body+='\n---\n*This pull request was automatically generated by '
+            pr_body+='[this GitHub Actions run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*'
             if [ -n "$release_url" ]; then
               pr_body="$pr_body\n\n**Release URL:** $release_url"
             fi
 
             # 4. Create PR via API
-            curl -s -X POST \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              -H "Accept: application/vnd.github+json" \
-              https://api.github.com/repos/${{ github.repository }}/pulls \
-              -d "$(jq -n \
+            if ! curl --fail \
+              --silent \
+              --show-error \
+              --location \
+              --retry 5 \
+              --header "Accept: application/vnd.github+json" \
+              --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              --data "$(jq --null-input \
                 --arg title "nvchecker: $entry $new_version" \
                 --arg body "$pr_body" \
                 --arg head "$branch_name" \
-                --arg base "master" \
-                '{title: $title, body: $body, head: $head, base: $base}')"
-            
-            # Return to main for the next iteration
-            git checkout master
+                --arg base "${{ github.head_ref || github.ref_name }}" \
+                '{title: $title, body: $body, head: $head, base: $base}')" \
+              https://api.github.com/repos/${{ github.repository }}/pulls
+            then
+              echo '::error::Failed to create a pull request using the GitHub API.'
+              # Delete created branch.
+              git push origin ":${branch_name}"
+              exit 1
+            fi
+
           done
